version: '3.8'

services:
  tg_news_bot:
    build: ./
    environment:
      DB_URL: 'postgresql+asyncpg://tgcmbot:tgcmbot@postgres:5432/tgcmbot'
      ADMIN_IDS: ${ADMIN_IDS:-96699669,}
      CHANNEL_ID: ${CHANNEL_ID:-69966996}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN:-TELEGRAM_TOKEN}

  postgres:
    image: postgres:13
    container_name: tgcmbot-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-tgcmbot}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-tgcmbot}
      POSTGRES_DB: ${POSTGRES_DB:-tgcmbot}
    volumes:
      - tgcmbot-postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER:-tgcmbot}" ]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always


volumes:
  tgcmbot-postgres:
